### ISSUE TITLE
Regarding the use of github pages

### ISSUE THREAD

**Issue by dummifiedme** [Maxence-L/notenote.link#5]
Can't we use github pages instead of Netlify? I was just wondering if we really have to use Netlify. I am a noob in all of this, I just want to publish a part of my notes from Obsidian. :)

**Comment by Maxence-L** [comment]
This is possible, with little changes, GitHub pages isn't compatible with the jekyll-toc module that I use. 

You can use this one, which won't break Github pages :

https://github.com/allejo/jekyll-toc

Follow me :

- Once you have forked the repo and gave it the name `username.github.io`, go to `_includes/content.html` and replace `{%- include toc.html -%}` by `{% include toc.html html=content %}``
- Remove the `toc.html` file and replace it with [this one](https://github.com/allejo/jekyll-toc/raw/master/_includes/toc.html).

Now, you can create your GitHub Page. If you need to set up a theme to start it, you can remove it in `_config.yml` and replace it with `theme: null`.

See :

![Screenshot](https://user-images.githubusercontent.com/56826661/104969992-5187b680-59ea-11eb-89cb-f2cc537a69f7.png)

I'll see if I can modify this plugin so that it has the same layout as the current one (which I like).

**Comment by mvallet91** [comment]
When using Pages but for a "Project page" (i.e. the url is "user.github.io/project") some of the links don't take in account the **baseurl** from `_config.yml`, so they point to "user.github.io". For example in [`layout.html`](https://github.com/Maxence-L/notenote.link/blob/master/_layouts/post.html#L29), [`header.html`](https://github.com/Maxence-L/notenote.link/blob/master/_includes/header.html#L61),  [`feed.html`](https://github.com/Maxence-L/notenote.link/blob/master/_includes/feed.html#L7) (also L27, L47 and L69) and [`content.html`](https://github.com/Maxence-L/notenote.link/blob/master/_includes/content.html#L10). 

I don't know if there's a reason for this, or if changing it would cause problems when publishing in Netlify or somewhere else, but adding `{{ site.baseurl }}` in those cases worked for me.

Thanks for the amazing plugin!
