### ISSUE TITLE
Applying another theme

### ISSUE THREAD

**Issue by one-data-cookie** [Maxence-L/notenote.link#6]
Stunning work, @Maxence-L! 👏 

I'd like to get this up and running, ideally using [Hyde](https://github.com/poole/hyde). Can you recommend which parts would be necessary to change to get at least a very similar feel, i.e. fixed left sidebar, same colour scheme, and fonts?

Or do you reckon it might be feasible to make this a subpage of a main website built with another theme (like Hyde)?

In the readme, you mention that you're thinking about having the ability to apply different themes. So, maybe this is already on your mind?

Any help would be much appreciated.

**Comment by Maxence-L** [comment]
Hi, thanks !

I set up Hyde to see if it was compatible with the `content.html` file which runs the house. Its skeleton is clearly different from notenote.link, which complicates the automatic retrieval of link addresses in [[wikilinks]]. 

Given that the `content.html` is already _very_ hacky, I'd go the CSS route and modify notenote.link to get the same feel. My 2cts on what could be changed safely :

- /_includes/header.html can be used to define the sidebar.
- /_includes/feed.html can be used to get the Hyde "full feed" homepage
- Other styling features can be set thoroughly through the asset/css/style.css

Currently, my aim is to increase the compatibility with Obsidian so that it works seamlessly.

**Comment by one-data-cookie** [comment]
Thank you for looking into this and providing me with directions, @Maxence-L. I took the suggested route and – after some pain with CSS – [made it work](https://github.com/one-data-cookie/digi-garden). Just about to fill it with my content any day now!

Cheers and thanks again. 👍
